### ISSUE TITLE
Edit CSS styling for Home, Post pages and User Post pages.

### ISSUE THREAD

**Issue by KaylaCharky** [KaylaCharky/SOEN-341#26]
As a user, I want to have an interface for my Home and Post pages so that it's aesthetically pleasing and easy to use.

### Acceptance Criteria

 - [x] CSS styling is applied to Home page and Post pages.

### Story Points

2

### Priority

Enhancement

### Risk

Low

### Sub-Tasks

- [x] Applied styling to Home page
- [x] Applied styling to Post page
- [x] Applied styling to User Post page
