### ISSUE TITLE
Edit CSS Styling on Account and Create Post

### ISSUE THREAD

**Issue by KaylaCharky** [KaylaCharky/SOEN-341#55]
As a user, I want to have an interface when creating posts, and changing my account settings so that it is easy to use and aesthetic. 

### Acceptance Criteria

 - [x] CSS styling is applied to Account page, Create Post page, and User Post page.

### Story Points

2

### Priority

Enhancement

### Risk

Low

### Sub-Tasks

- [x] Applied styling to Account page
- [x] Applied styling to Create Post page
